apiVersion: v1
kind: Secret
metadata:
  name: springboot-db-secret
  namespace: spring-boot-postgres-demo
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: jdbc:postgresql://springboot-postgres-db.ct26qwu60idx.us-east-2.rds.amazonaws.com:5432/testdb
  SPRING_DATASOURCE_USERNAME: appuser
  SPRING_DATASOURCE_PASSWORD: spring*12345
