apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: spring-boot-postgres-demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: spring-boot-postgres
    app.kubernetes.io/instance: spring-boot-app
  ports:
    - port: 8080
      targetPort: 8080
